[package]
org = "ballerina"
name = "observe"
version = "1.4.0"
distribution = "2201.10.0"
export = ["observe", "observe.mockextension" ]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/observe-native-1.4.0-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "observe"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-trace"
version = "1.0.0"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-testing"
version = "1.0.0"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-common"
version = "1.0.0"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-semconv"
version = "1.0.0-alpha"
